export const SST_FULL_PARAGRAPHS = [
  "OBJETO",
  "Establecer los requerimientos y elementos básicos a considerar para la identificación de peligros, evaluación, valoración y determinación de control de riesgo e impactos, con la finalidad de controlar y establecer las medidas necesarias, para minimizar la ocurrencia de eventos que puedan resultar con lesiones a los trabajadores, a terceros, daños materiales o impacto ambiental en la organización.",
  "ALCANCE",
  "Aplica a toda actividad ejecutada o contratada por COOPROAGRO LTDA",
  "DEFINICIONES Y ABREVIATURAS",
  "Riesgo: Es una medida del potencial de pérdidas económicas o humanas en términos de la probabilidad de ocurrencia de un evento no deseado junto con las medidas de sus consecuencias adversas.",
  "Peligro: Es una fuente o situación con potencial de daño en términos de lesión o enfermedad, daño a la propiedad, al ambiente de trabajo o una combinación de éstos.",
  "Actividad Rutinaria: Operaciones y procedimientos normales que se ejecutan en la organización.",
  "Actividad No Rutinaria: Procedimientos ocasionales que se ejecutan en la organización.",
  "Incidente: Evento con el potencial para llegar a ser un accidente.",
  "Acto Inseguro: Todo acto que realiza un trabajador de manera insegura o inapropiada y que facilita la ocurrencia de un accidente de trabajo con afectación al medio ambiente, la integridad física de las personas o de la instalación.",
  "Condición Insegura: Situación que se presenta en el lugar de trabajo y que se caracteriza por la presencia de riesgos no controlados que pueden generar accidente de trabajo con afectación al medio ambiente, la integridad física de las personas o de la instalación.",
  "Accidente de trabajo: Todo suceso repentino que sobrevenga por causa o con ocasión del trabajo, y que produzca en el trabajador una lesión orgánica, una perturbación funcional o psiquiátrica, una invalidez o la muerte",
  "Enfermedad laboral: Se considera enfermedad laboral la contraída como resultado de la exposición a factores de riesgo inherentes a la actividad laboral o del medio en el que el trabajador se ha visto obligado a trabajar.",
  "Factor de Riesgo: Todo elemento cuya presencia o modificación tenga la probabilidad de producir un daño a quien está expuesto.",
  "Fuente Generadora: Condición que está generando el factor de riesgo.",
  "Efecto o Consecuencia: Posible efecto que el Factor de Riesgo puede generar en el ámbito de la salud del trabajador, el ambiente, el proceso, los equipos.",
  "Priorización de los factores de riesgo:   Es un ejercicio por medio del cual se otorgan valores convencionales a los factores de riesgo de modo que se pueda jerarquizar de acuerdo a su importancia relativa.",
  "Medidas de Prevención y Control: Acciones actuales para eliminar o minimizar el riesgo que puede generar un accidente o un incidente.",
  "Evaluación de los riesgos: Proceso para determinar el nivel de riesgo, asociado al nivel de probabilidad y el nivel de consecuencia.",
  "Efecto del peligro: Es la consecuencia más probable que puede llegar a generar un peligro existente en el lugar de trabajo.",
  "Personal Expuesto: Número de colaboradores que se ven afectados en forma directa o indirecta por uno o más peligros durante la realización del trabajo.",
  "Controles existentes: Son las medidas de control que en la actualidad implementa la organización, con el fin de minimizar la ocurrencia de accidentes de trabajo y enfermedades laborales.",
  "Probabilidad: Posibilidad de que se produzca el efecto de un peligro, en función de la frecuencia de exposición, intensidad de la exposición, número de expuestos, actos y condiciones inseguras.",
  "Severidad: Es el nivel esperado de las consecuencias por la presencia del aspecto o peligro, o materialización del impacto o riesgo, medido en extensión del daño, pérdidas económicas y número o tipo de lesiones. Hay que tener en cuenta tiempo de interrupción de la operación, daño a la imagen de la compañía y daño a las personas y al medio ambiente.",
  "Consecuencia: Es el resultado más probable y esperado si el peligro no se corrige ni se controla, se estima según el potencial de gravedad.",
  "Estimación Del Riesgo: Está dada de acuerdo con la combinación realizada entre la probabilidad, la exposición y las consecuencias.",
  "Riesgo Tolerable: Riesgo que se ha reducido a un nivel que la Organización puede soportar respecto a sus obligaciones legales y su propia política.",
  "Medidas de Prevención y Control: Medidas de eliminación o mitigación de los peligros identificados y que se ponen en práctica n la fuente de origen, en el medio de transmisión, en las personas o en el método.",
  "Matriz de identificación de peligros, evaluación y valoración de los riesgos: Es un estudio de las condiciones de trabajo mediante el cual se hace un reconocimiento pormenorizado de los factores de riesgo a los que están expuestos los trabajadores en un lugar específico; determinando los efectos que puede ocasionar a la salud de los trabajadores y a la estructura organizacional.",
  "SG-SST: Sistema de gestión en Seguridad y salud en el trabajo",
  "4. DESCRIPCION",
  "4.1. CONDICIONES GENERALES",
  "La identificación de peligros, evaluación y valoración de los riesgos, es un estudio de observación y análisis para reconocimiento y valoración de las condiciones inseguras; se constituye en una tarea fundamental en la cual se identifican y localizan los diferentes riesgos presentes en las áreas de trabajo de la organización; para luego seleccionar las alternativas de control apropiadas antes de que se presenten los accidentes y las enfermedades laborales.",
  "Al realizar la identificación de peligros, evaluación y valoración de los riesgos, se debe tener concordancia con el proceso u operación, reconociendo todas las tareas, materias primas, equipos, la organización, al igual se debe involucrar todas las disciplinas relacionadas con la salud en el trabajo.",
  "4.2. DESARROLLO DE ACTIVIDADES PARA REALIZAR LA IDENTIFICACIÓN DE PELIGROS, VALORACIÓN Y DETERMINACIÓN DE CONTROL DE RIESGO.",
  "4.2.1. Inspección general sistemática.",
  "Al realizar esta inspección se requiere que el encargado SST, tenga una preparación previa sobre “qué y donde” va a buscar los peligros. Dado lo anterior, se hace necesario el diligenciamiento del Anexo 1. Lista de chequeo para la identificación de peligros, en todos los centros de trabajo.",
  "PASOS DEL PROCEDIMIENTO",
  "A continuación se detallan las actividades que se deben realizar, y que son responsabilidad de los encargados SST y/o encargados.",
  "Actividad\r\u0007",
  "Descripción\r\u0007",
  "\u0007",
  "1. Entrada de información\r\u0007",
  "Describir detalladamente cada una de las actividades realizadas y el tipo de actividad (Rutinaria o No Rutinaria)\r\u0007",
  "\u0007",
  "\u0007",
  "Visitar el sitio de trabajo.\r\u0007",
  "\u0007",
  "\u0007",
  "Verificar condiciones de seguridad\r\u0007",
  "\u0007",
  "\u0007",
  "Organigrama de la empresa y descripción del cargo.\r\u0007",
  "\u0007",
  "2. Identificación de peligros.",
  "\u0007",
  "Identificar los peligros asociados a las actividades descritas.",
  "a) actividades rutinarias y no rutinarias; b) actividades de todas las personas que tienen acceso al sitio de trabajo (incluso contratistas y visitantes); c) comportamiento, aptitudes y otros factores humanos; d) los peligros identificados que se originan fuera del lugar de trabajo con capacidad de afectar adversamente la salud y la seguridad de las personas que están bajo el control de la organización en el lugar de trabajo; e) los peligros generados en la vecindad del lugar de trabajo por actividades relacionadas con el trabajo controladas por la organización; f) Infraestructura, equipo y materiales en el lugar de trabajo, ya sean suministrados por la organización o por otros; g) Cambios realizados o propuestos en la organización, sus actividades o los materiales; h) modificaciones al sistema de gestión integral, incluidos los cambios temporales y sus impactos sobre las operaciones, procesos y actividades; i) cualquier obligación legal aplicable relacionada con la valoración del riesgo y la implementación de los controles necesarios, j) el diseño de áreas de trabajo, procesos, instalaciones, maquinaria/equipos, procedimientos de operación y organización del trabajo, incluida su adaptación a las aptitudes humanas.\r\u0007",
  "\u0007",
  "3. Identificación de efectos.\r\u0007",
  "Describir los efectos que pueden ocasionar los peligros identificados considerando las personas, los activos y el medio ambiente.\r\u0007",
  "\u0007",
  "4. Establecer el tiempo de exposición\r\u0007",
  "Determinar mediante información recibida del trabajador y el jefe inmediato las horas reales o promedio durante el día, en las que los trabajadores se encuentran expuestos al peligro identificado.\r\u0007",
  "\u0007",
  "5. Establecer el personal expuesto\r\u0007",
  "Utilizar la información recibida de todos los empleados de un mismo cargo, consolidando la información por actividad.  \r\u0007",
  "\u0007",
  "6. Valoración del riesgo\r\u0007",
  "Cuantificar los riesgos de acuerdo a la metodología indicada en este procedimiento.  \r\u0007",
  "\u0007",
  "7. Identificar las medidas de prevención y control\r\u0007",
  "Describir las acciones que se están realizando para disminuir y controlar el peligro identificado. Controles de Eliminación,  Sustitución, de ingeniería, administrativos y Elementos de Protección Personal\r\u0007",
  "\u0007",
  "8. Establecer medidas adicionales de control\r\u0007",
  "Recomendar las medidas de control y/o eliminación del riesgo con el fin de llevarlo a niveles tolerables para la organización.\r\u0007",
  "\u0007",
  "9. Actualización de la matriz de identificación de peligros  \r\u0007",
  "Se aplicarán las actividades de este procedimiento, cuando se presenten cambios de infraestructura, equipos, métodos, operaciones, nuevos productos, nuevas tecnologías o nuevos cargos.\r\u0007",
  "\u0007",
  "10. Divulgación\r\u0007",
  "Se realizará a todo el personal en las inducciones, re inducciones y charlas de cinco minutos.\r\u0007",
  "\u0007",
  "METODOLÒGIA.",
  "Identificar los peligros asociados a las actividades en el lugar de trabajo y valorar los riesgos derivados de los peligros para poder determinar las medidas de control que se deben tomar para establecer y mantener la seguridad y salud de los trabajadores y otras partes interesadas. De acuerdo a la metodología de la guía técnica Colombiana (GTC-45).",
  "ACTIVIDADES PARA IDENTIFICAR LOS PELIGROS, VALORAR LOS RIESGOS Y DETERMINAR LAS MEDIDAS DE CONTROL.",
  "Registro de recopilación de información: utilizar la matriz de riesgos (descrita en la GTC 45 - Anexo B), la cual requiere la siguiente información:",
  "Proceso",
  "Zona o lugar",
  "Actividad",
  "Tarea (Rutinaria o No)",
  "Peligro (descripción y clasificación)",
  "Efectos posibles",
  "Controles existentes (fuente, medio e individuo)",
  "Evaluación del riesgo (Niveles de: deficiencia, exposición, probabilidad, consecuencia, riesgo e intervención e interpretación nivel de riesgo)",
  "Valoración del riesgo (Aceptabilidad del riesgo).",
  "Criterios para establecer controles (N° de expuestos, peor consecuencia y existencia requisito legal)",
  "Medidas de intervención (eliminación, sustitución, controles de ingeniería y administrativo, equipos y EPP)",
  "Desarrollo de la matriz:",
  "a. Clasificación de procesos, actividades y tareas: identificar las actividades de trabajo, agruparlas y tener en cuenta lo siguiente:",
  "Descripción del proceso, actividad o tarea (duración y frecuencia)",
  "Interacción con otros procesos, actividades y tareas.",
  "Número de trabajadores involucrados.",
  "Partes interesadas (visitantes, contratistas, entre otros)",
  "Procedimientos e instructivos de trabajo relacionados.",
  "Maquinas, equipos y/o herramientas.",
  "Manipulación de materiales.",
  "Sustancias utilizadas o encontradas en el lugar de trabajo (humos, gases, vapores, líquidos, polvos, sólidos), su contenido y recomendaciones (hoja de seguridad).",
  "Requisitos legales y normas aplicables a la actividad.",
  "Medidas de control establecidas.",
  "Sistemas de emergencia (equipo de emergencia, rutas de evacuación, comunicación interna y apoyo externo)",
  "Histórico de incidentes asociado con la actividad a valorar.",
  "b.  Identificación, descripción y clasificación de los peligros: se toma como referencia la tabla de peligros (anexo A de la GTC 45), la cual clasifica los peligros así:",
  "Biológico.",
  "Físico.",
  "Químico.",
  "Psicosocial.",
  "Biomecánicos.",
  "Condiciones de seguridad.",
  "Fenómenos naturales.",
  "c. Efectos Posibles: establecerlos teniendo en cuenta el nivel de daño que pueda generar  sobre la integridad o salud de los trabajadores.",
  "d. Identificación de los controles existentes: para cada uno de los peligros y clasificarlos en: fuente, medio e individuo; considerar los controles que se  han implementado para disminuir el riesgo, por ejemplo: inspecciones, ajustes a procedimientos, entre otros.",
  "e. Evaluación del riesgo: determinar la probabilidad de que ocurran eventos específicos y la magnitud de sus consecuencias mediante el uso sistemático de la información disponible;      (con base en  la GTC 45), se determinan los siguientes criterios:",
  "Descripción de los niveles de daño.",
  "Determinación del nivel de deficiencia.",
  "Determinación del nivel de exposición.",
  "Determinación del nivel de probabilidad.",
  "Significado de los diferentes niveles de probabilidad.",
  "Determinación del nivel de consecuencias.",
  "Determinación del nivel de riesgo.",
  "Significado del nivel de riesgo y de intervención.",
  "Para evaluar el nivel  de riesgo (NR) se debe determinar lo siguiente:",
  "NR= NP x NC \t\t\t\ten donde:               NP = Nivel de probabilidad",
  "NC=  Nivel de consecuencia",
  "Tabla determinación de riesgo.",
  "Tabla 12 Nivel de Riesgo (NR)\r\u0007",
  "\u0007",
  "NIVEL DE RIESGO Y DE INTERVENCIÓN\r\u0007",
  "NIVEL DE PROBABILIDAD (NP)\r\u0007",
  "\u0007",
  "NR = NP x NC\r\u0007",
  "40 - 24\r\u0007",
  "20 - 10\r\u0007",
  "8 - 6\r\u0007",
  "4 - 2\r\u0007",
  "\u0007",
  "NIVEL DE CONCECUENCIAS (NC)\r\u0007",
  "100\r\u0007",
  "I\r\u0007",
  "I\r\u0007",
  "I\r\u0007",
  "II\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "4000-2400\r\u0007",
  "200-1200\r\u0007",
  "800-600\r\u0007",
  "400-200\r\u0007",
  "\u0007",
  "\u0007",
  "60\r\u0007",
  "I\r\u0007",
  "I\r\u0007",
  "II\r\u0007",
  "II 240\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "2400-1440\r\u0007",
  "1200-600\r\u0007",
  "480-360\r\u0007",
  "III 120\r\u0007",
  "\u0007",
  "\u0007",
  "25\r\u0007",
  "I\r\u0007",
  "II\r\u0007",
  "II\r\u0007",
  "III\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "1000 - 600\r\u0007",
  "500-250\r\u0007",
  "200-150\r\u0007",
  "100-50\r\u0007",
  "\u0007",
  "\u0007",
  "10\r\u0007",
  "II\r\u0007",
  "II 200\r\u0007",
  "III\r\u0007",
  "III 40\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "400 -240\r\u0007",
  "III 100\r\u0007",
  "80-60\r\u0007",
  "IV  20\r\u0007",
  "\u0007",
  "Tabla nivel de determinación de riesgo.",
  "Tabla 13 Significados de los niveles de Riesgo  (NR)\r\u0007",
  "\u0007",
  "NIVEL DE RIESGO Y DE INTREVENCIÓN\r\u0007",
  "NR\r\u0007",
  "SIGNIFICADO\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "I\r\u0007",
  "4000-600\r\u0007",
  "Situación crítica. Corrección urgente. Se debe establecer un programa de gestión\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "II\r\u0007",
  "500 – 150\r\u0007",
  "Corregir y adoptar medidas de control operacional\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "III\r\u0007",
  "120 – 40\r\u0007",
  "Mejorar si es posible. Sería conveniente justificar la intervención y su rentabilidad\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "IV\r\u0007",
  "20\r\u0007",
  "Mantener las medidas de control existentes, pero se deberían considerar soluciones o mejoras y se deben hacer comprobaciones periódicas para asegurar que el riesgo aún es nivel IV\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "A su vez, para determinar el NP se requiere:",
  "NP= ND X NE \t\t    en donde: \t\t\t\t ND= Nivel de deficiencia",
  "NE= Nivel de exposición",
  "f. Valoración del riesgo: evaluar la suficiencia de los controles existentes, la definición de los criterios de aceptabilidad del riesgo y la decisión de aceptarlos o no, (según lo descrito en la GTC 45).",
  "Aceptabilidad del riesgo.",
  "g. Criterios para establecer controles: determinar qué criterios se necesitan para priorizar los controles existentes, de acuerdo a:",
  "Número de trabajadores expuestos.",
  "Peor consecuencia",
  "Existencia de requisito legal asociado.",
  "h. Medidas de intervención: determinar si los controles existentes son suficientes o necesitan mejorarse, o si requieren nuevos controles; priorizar con base en el principio de eliminación de peligros, reducción de riesgos, es decir reducción de la probabilidad de ocurrencia o la severidad potencial de la lesión o daño, clasificar de acuerdo a:",
  "(GTC 45–Anexo B)",
  "Eliminación",
  "Sustitución",
  "Controles de ingeniería",
  "Señalización y Controles administrativos",
  "Equipos y elementos de protección personal.",
  "i. Actualización: la matriz de identificación de peligros y valoración del riesgo se actualizará anualmente, sin embargo se manejan ciertos criterios y actividades que permiten evaluar periódicamente los cambios evidenciados y mantener actualizada la matriz, como:",
  "Necesidad de responder a nuevos peligros.",
  "Necesidad de responder a cambios que la propia empresa ha llevado a cabo.",
  "Investigación de incidentes, situaciones de emergencia o los resultados de simulacros y del mismo Plan de emergencia.",
  "Cambios en la legislación y",
  "Revisiones periódicas por medio de los Programas de Inspecciones.",
  "Observaciones hechas por las partes interesadas",
  "Nuevos proyectos, cambios de ingeniería y/o procesos.",
  "Pedidos de acciones correctivas.",
  "Cese de actividades o aspectos que dan lugar condiciones inseguras.",
  "Cumplimiento total o parcial de los objetivos y metas vinculados.",
  "Nuevos requisitos legales o modificación de los existentes.",
  "Reporte de  Tarjeta REPORTA.",
  "4.6 DIVULGACIÒN.",
  "La divulgación de los cambios efectuados en la Matriz de identificación de peligros, evaluación y valoración de los riesgos, se realizara por parte de los encargados SST, y/o personal designado para tal fin, a todos los colaboradores que hacen parte del centro de trabajo.",
  "En el momento de que se genere una eventualidad tal como: cambio de personal o de labor,  cambio de instalaciones, remplazos por incapacidades o vacaciones, se deberá realizar oportunamente la divulgación de los nuevos riesgos a los cuales está expuesto por cualquier mecanismo de los determinados en el procedimiento de comunicaciones y a través del  Notificación de riesgos para trabajadores.",
  "5. ANEXOS",
  "SST MT 02Matriz de identificación de peligros, evaluación y valoración de los riesgos",
  "SST RE- 80 Tarjeta REPORTA.",
  "SST RE- 83 Notificación de riesgos para trabajadores",
  "Lista de chequeo para identificación de peligros",
  "ANEXO 1",
  "LISTA DE CHEQUEO PARA IDENTIFICACIÓN DE PELIGROS \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Proyecto y/o proceso:\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Fecha\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Clasificación del peligro\r\u0007",
  "Peligros\r\u0007",
  "Aplica\r\u0007",
  "Condición que lo genera (Fuente)\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Si\r\u0007",
  "No\r\u0007",
  "\u0007",
  "\u0007",
  "RUIDO\r\u0007",
  "Continuo\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Impacto\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Intermitente\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "ILUMINACIÓN \r\u0007",
  "Exceso de luz\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Deficiente luz\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "VIBRACIÓN\r\u0007",
  "Segmentado (mano y brazo)\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "RADIACIONES  \r\u0007",
  "Ionizantes (Rayos X, alfa, beta, gamma)\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "No ionizantes (Láser, Ultravioleta, Infrarrojos, Radiofrecuencia)\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "AMBIENTE TÉRMICO \r\u0007",
  "Temperaturas altas por calor\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Temperaturas bajas por frío \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Humedad\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "QUÍMICO \r\u0007",
  "Inhalación de material particulado\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Humos\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Gases y vapores\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Polvos orgánicos, inorgánicos\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "BIOLÓGICO\r\u0007",
  "Picaduras\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Mordeduras\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Virus, bacterias, hongos\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Parásitos\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "ERGONÓMICO \r\u0007",
  "Posturas inadecuadas\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Posturas sedentes\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Posturas prolongadas de pie\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Esfuerzos físicos (desplazamiento de equipos, etc).\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Movimiento repetitivo\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Manipulación manual de cargas\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "PSICOSOCIAL\r\u0007",
  "Repetitividad y/o monotonía.\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Elevada cantidad de trabajo\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Elevada dificultad del trabajo\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Jornada laboral extensa\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Trabajo por turnos, trabajo nocturno \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Ausencia de actividades del programa de bienestar\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Inestabilidad laboral\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Deficiente comunicación \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Deficiente trabajo en equipo \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Deficientes relaciones, interacciones, cohesión. \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "ELECTRICIDAD\r\u0007",
  "Alta Tensión\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Media Tensión\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Baja Tensión\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Tomas e interruptores en mal estado.\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Cables sueltos sin entubar\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Electricidad Estática\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "EXPLOSIÓN E INCENDIOS\r\u0007",
  "Humos\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Manejo de sustancias químicas\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Almacenamiento de sustancias combustibles \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Presencia de gas natural,                    gas propano\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Vehículos a gas, gasolina\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Electrodomésticos\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Material combustible\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "MECÁNICO\r\u0007",
  "Manejo de elementos corto punzantes   \u000b\u000b \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Atrapamiento por mecanismos o equipos en movimiento\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Choques o volcamientos por vehículos\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Proyección de partículas\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Manejo de herramientas, materiales.\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Lesiones por accidentes de transito\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Maquinaria sin protección \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "LOCATIVO\r\u0007",
  "Caídas por estructura e instalaciones (pisos, escaleras) \u000b        \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Caídas al mismo nivel y a diferente nivel (desniveles, zanjas, huecos, etc.)\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Golpes por sistemas inadecuados de almacenamiento \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Golpes o caídas por falta de orden y aseo\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Caídas de objetos\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Derrumbes, deslizamientos \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Golpes o caídas por falta  demarcación o señalización. \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "CONDICIONES DE SEGURIDAD\r\u0007",
  "Trabajos en alturas\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Excavaciones\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Espacios confinados \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "PÚBLICO\r\u0007",
  "Atracos, robos\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Terrorismo, atentados\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "FENÓMENOS NATURALES\r\u0007",
  "Terremotos, sismos        \r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Inundaciones\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Precipitaciones                                 (lluvias, granizadas, heladas)\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "Tormentas eléctricas\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "OTROS\r\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007",
  "\u0007"
];
export const SST_FULL_TABLES = [
  [
    "Actividad",
    "Descripción",
    "1. Entrada de información",
    "Describir detalladamente cada una de las actividades realizadas y el tipo de actividad (Rutinaria o No Rutinaria)",
    "Visitar el sitio de trabajo.",
    "Verificar condiciones de seguridad",
    "Organigrama de la empresa y descripción del cargo.",
    "2. Identificación de peligros.",
    "Identificar los peligros asociados a las actividades descritas.\ra) actividades rutinarias y no rutinarias; b) actividades de todas las personas que tienen acceso al sitio de trabajo (incluso contratistas y visitantes); c) comportamiento, aptitudes y otros factores humanos; d) los peligros identificados que se originan fuera del lugar de trabajo con capacidad de afectar adversamente la salud y la seguridad de las personas que están bajo el control de la organización en el lugar de trabajo; e) los peligros generados en la vecindad del lugar de trabajo por actividades relacionadas con el trabajo controladas por la organización; f) Infraestructura, equipo y materiales en el lugar de trabajo, ya sean suministrados por la organización o por otros; g) Cambios realizados o propuestos en la organización, sus actividades o los materiales; h) modificaciones al sistema de gestión integral, incluidos los cambios temporales y sus impactos sobre las operaciones, procesos y actividades; i) cualquier obligación legal aplicable relacionada con la valoración del riesgo y la implementación de los controles necesarios, j) el diseño de áreas de trabajo, procesos, instalaciones, maquinaria/equipos, procedimientos de operación y organización del trabajo, incluida su adaptación a las aptitudes humanas.",
    "3. Identificación de efectos.",
    "Describir los efectos que pueden ocasionar los peligros identificados considerando las personas, los activos y el medio ambiente.",
    "4. Establecer el tiempo de exposición",
    "Determinar mediante información recibida del trabajador y el jefe inmediato las horas reales o promedio durante el día, en las que los trabajadores se encuentran expuestos al peligro identificado.",
    "5. Establecer el personal expuesto",
    "Utilizar la información recibida de todos los empleados de un mismo cargo, consolidando la información por actividad.",
    "6. Valoración del riesgo",
    "Cuantificar los riesgos de acuerdo a la metodología indicada en este procedimiento.",
    "7. Identificar las medidas de prevención y control",
    "Describir las acciones que se están realizando para disminuir y controlar el peligro identificado. Controles de Eliminación,  Sustitución, de ingeniería, administrativos y Elementos de Protección Personal",
    "8. Establecer medidas adicionales de control",
    "Recomendar las medidas de control y/o eliminación del riesgo con el fin de llevarlo a niveles tolerables para la organización.",
    "9. Actualización de la matriz de identificación de peligros",
    "Se aplicarán las actividades de este procedimiento, cuando se presenten cambios de infraestructura, equipos, métodos, operaciones, nuevos productos, nuevas tecnologías o nuevos cargos.",
    "10. Divulgación",
    "Se realizará a todo el personal en las inducciones, re inducciones y charlas de cinco minutos."
  ],
  [
    "Tabla 12 Nivel de Riesgo (NR)",
    "NIVEL DE RIESGO Y DE INTERVENCIÓN",
    "NIVEL DE PROBABILIDAD (NP)",
    "NR = NP x NC",
    "40 - 24",
    "20 - 10",
    "8 - 6",
    "4 - 2",
    "NIVEL DE CONCECUENCIAS (NC)",
    "100",
    "I",
    "I",
    "I",
    "II",
    "4000-2400",
    "200-1200",
    "800-600",
    "400-200",
    "60",
    "I",
    "I",
    "II",
    "II 240",
    "2400-1440",
    "1200-600",
    "480-360",
    "III 120",
    "25",
    "I",
    "II",
    "II",
    "III",
    "1000 - 600",
    "500-250",
    "200-150",
    "100-50",
    "10",
    "II",
    "II 200",
    "III",
    "III 40",
    "400 -240",
    "III 100",
    "80-60",
    "IV  20"
  ],
  [
    "Tabla 13 Significados de los niveles de Riesgo  (NR)",
    "NIVEL DE RIESGO Y DE INTREVENCIÓN",
    "NR",
    "SIGNIFICADO",
    "I",
    "4000-600",
    "Situación crítica. Corrección urgente. Se debe establecer un programa de gestión",
    "II",
    "500 – 150",
    "Corregir y adoptar medidas de control operacional",
    "III",
    "120 – 40",
    "Mejorar si es posible. Sería conveniente justificar la intervención y su rentabilidad",
    "IV",
    "20",
    "Mantener las medidas de control existentes, pero se deberían considerar soluciones o mejoras y se deben hacer comprobaciones periódicas para asegurar que el riesgo aún es nivel IV"
  ],
  [
    "LISTA DE CHEQUEO PARA IDENTIFICACIÓN DE PELIGROS",
    "Proyecto y/o proceso:",
    "Fecha",
    "Clasificación del peligro",
    "Peligros",
    "Aplica",
    "Condición que lo genera (Fuente)",
    "Si",
    "No",
    "RUIDO",
    "Continuo",
    "Impacto",
    "Intermitente",
    "ILUMINACIÓN",
    "Exceso de luz",
    "Deficiente luz",
    "VIBRACIÓN",
    "Segmentado (mano y brazo)",
    "RADIACIONES",
    "Ionizantes (Rayos X, alfa, beta, gamma)",
    "No ionizantes (Láser, Ultravioleta, Infrarrojos, Radiofrecuencia)",
    "AMBIENTE TÉRMICO",
    "Temperaturas altas por calor",
    "Temperaturas bajas por frío",
    "Humedad",
    "QUÍMICO",
    "Inhalación de material particulado",
    "Humos",
    "Gases y vapores",
    "Polvos orgánicos, inorgánicos",
    "BIOLÓGICO",
    "Picaduras",
    "Mordeduras",
    "Virus, bacterias, hongos",
    "Parásitos",
    "ERGONÓMICO",
    "Posturas inadecuadas",
    "Posturas sedentes",
    "Posturas prolongadas de pie",
    "Esfuerzos físicos (desplazamiento de equipos, etc).",
    "Movimiento repetitivo",
    "Manipulación manual de cargas",
    "PSICOSOCIAL",
    "Repetitividad y/o monotonía.",
    "Elevada cantidad de trabajo",
    "Elevada dificultad del trabajo",
    "Jornada laboral extensa",
    "Trabajo por turnos, trabajo nocturno",
    "Ausencia de actividades del programa de bienestar",
    "Inestabilidad laboral",
    "Deficiente comunicación",
    "Deficiente trabajo en equipo",
    "Deficientes relaciones, interacciones, cohesión.",
    "ELECTRICIDAD",
    "Alta Tensión",
    "Media Tensión",
    "Baja Tensión",
    "Tomas e interruptores en mal estado.",
    "Cables sueltos sin entubar",
    "Electricidad Estática",
    "EXPLOSIÓN E INCENDIOS",
    "Humos",
    "Manejo de sustancias químicas",
    "Almacenamiento de sustancias combustibles",
    "Presencia de gas natural,                    gas propano",
    "Vehículos a gas, gasolina",
    "Electrodomésticos",
    "Material combustible",
    "MECÁNICO",
    "Manejo de elementos corto punzantes",
    "Atrapamiento por mecanismos o equipos en movimiento",
    "Choques o volcamientos por vehículos",
    "Proyección de partículas",
    "Manejo de herramientas, materiales.",
    "Lesiones por accidentes de transito",
    "Maquinaria sin protección",
    "LOCATIVO",
    "Caídas por estructura e instalaciones (pisos, escaleras)",
    "Caídas al mismo nivel y a diferente nivel (desniveles, zanjas, huecos, etc.)",
    "Golpes por sistemas inadecuados de almacenamiento",
    "Golpes o caídas por falta de orden y aseo",
    "Caídas de objetos",
    "Derrumbes, deslizamientos",
    "Golpes o caídas por falta  demarcación o señalización.",
    "CONDICIONES DE SEGURIDAD",
    "Trabajos en alturas",
    "Excavaciones",
    "Espacios confinados",
    "PÚBLICO",
    "Atracos, robos",
    "Terrorismo, atentados",
    "FENÓMENOS NATURALES",
    "Terremotos, sismos",
    "Inundaciones",
    "Precipitaciones                                 (lluvias, granizadas, heladas)",
    "Tormentas eléctricas",
    "OTROS"
  ]
];
